name: build
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces:
            containerd-shim-slight-v1 -> target
            containerd-shim-spin-v1 -> target
      - name: "Install Rust Wasm targets"
        run: |
          rustup target add wasm32-wasi
          rustup target add wasm32-unknown-unknown
      - name: build
        run: |
          make build
          rm -rf ./bin && mkdir ./bin
          cp containerd-shim-slight-v1/target/release/containerd-shim-*-v1 bin/
          cp containerd-shim-spin-v1/target/release/containerd-shim-*-v1 bin/
      - name: build k3d demo
        run: make build-image
        working-directory: ./deployments/k3d
