name: ci
on:
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: build
    runs-on: ${{ matrix.config.os }}
    strategy:
        matrix:
          config:
            - {
                os: "ubuntu-latest",
                arch: "x86_64",
              }
            - {
                os: "ubuntu_latest",
                arch: "aarch64"
              }
    steps:
      uses: ./.github/workflows/build.yaml
      env:
        ARCH: ${{ matrix.config.arch }}
      
